masl_clientid = "38dcd06e-ad0c-4509-ae3f-2690ff4e3362"
msal_authority= "https://login.microsoftonline.com/94cd8921-8f5c-4862-83a8-aeaab06c4082"
msal_redirect = "/"
msal_post = "/"


domain = "crm.hub-bnk.com/"
relative_path = "bitrix/tools/biconnector/pbi.php"
key = "EHha0VZcT91SEUgpkDuXahyfsSSPM8wLbr"
bignumber = "3274"
cod_shhh = "oz2yjj0b0qk8ys8d"

url_add = "https://crm.hub-bnk.com/rest/3274/oz2yjj0b0qk8ys8d/crm.item.add?entityTypeId=154&"
url_update = "https://crm.hub-bnk.com/3274/oz2yjj0b0qk8ys8d/crm.item.update?entityTypeId=154&"
url_delete = "https://crm.hub-bnk.com/rest/3274/oz2yjj0b0qk8ys8d/crm.item.delete?entityTypeId=154&"


deal = "DEAL_ID"
title = "TITLE"
id = "ID"
oportunidade = "OPPORTUNITY"
contato = "CONTACT"
assigned = "ASSIGNED_BY"
category = "CATEGORY_ID"


#CLIENTE
courier = "429"
#PRODUTO
arabian = "451"
#REPASSE
bigby = "453"

#SIGLA_ASSESSOR
VAR_SIGLA_ASSESSOR = "UF_CRM_235_SIGLA_ASSESSOR" 

#NOME_CLIENTE
VAR_NOME_CLIENTE = "UF_CRM_235_NOME_CLIENTE"

#DATA_ENTRADA_CLIENTE
VAR_DATA_ENTRADA_CLIENTE = "UF_CRM_235_DATA_ENTRADA_CLIENTE"

#CATEGORIA
VAR_CATEGORIA = "UF_CRM_235_CATEGORIA"

#ATIVO
VAR_ATIVO = "UF_CRM_235_ATIVO"

#ROA_HEAD
VAR_ROA_HEAD = "UF_CRM_235_ROA_HEAD"

#ROA_REC
VAR_ROA_REC = "UF_CRM_235_ROA_REC"

#PL_APLICADO
VAR_PL_APLICADO = "UF_CRM_235_PL_APLICADO"

#DATA_ATIVO
VAR_DATA_ATIVO = "UF_CRM_235_DATA_ATIVO"

#DATA_VENC
VAR_DATA_VENC = "UF_CRM_235_DATA_VENC"

#ID_CLIENTE
VAR_ID_CLIENTE = "UF_CRM_235_ID_CLIENTE"

#EMPRESA
VAR_EMPRESA = "UF_CRM_235_EMPRESA"

#RETORNO
VAR_RETORNO = "UF_CRM_235_RETORNO"

#REPASSE
VAR_REPASSE = "UF_CRM_235_REPASSE"

#ID_EMAIL
VAR_ID_EMAIL = "UF_CRM_235_ID_EMAIL"

#SIMULADOR_REPASSE_INVESTSMART
VAR_REPASSE_INVESTSMART = "UF_CRM_235_SIMULADOR_REPASSE_INVESTSMART"

#SIMULADOR_REPASSE_SEGUROS
VAR_REPASSE_SEGUROS = "UF_CRM_235_SIMULADOR_REPASSE_SEGUROS"

#SIMULADOR_REPASSE_CAMBIO
VAR_REPASSE_CAMBIO = "UF_CRM_235_REPASSE_CAMBIO"

#SIMULADOR_REPASSE_CREDITO
VAR_REPASSE_CREDITO = "UF_CRM_235_REPASSE_CREDITO"

#SIMULADOR_REPASSE_IMOVEL
VAR_REPASSE_IMOVEL = "UF_CRM_235_REPASSE_IMOVEL"

VAR1 = "ufCrm235SiglaAssessor"
VAR2 = "ufCrm235NomeCliente"
VAR3 = "ufCrm235DataEntradaCliente"
VAR4 = "ufCrm235Categoria"
VAR5 = "ufCrm235Ativo"
VAR6 = "ufCrm235RoaHead"
VAR7 = "ufCrm235RoaRec"
VAR8 = "ufCrm235PlAplicado"
VAR9 = "ufCrm235DataAtivo"
VAR10= "ufCrm235DataVenc"
VAR11= "ufCrm235IdCliente"
VAR12= "ufCrm235Empresa"
VAR13= "ufCrm235Retorno"
VAR14= "ufCrm235Repasse"
VAR15= "ufCrm235IdEmail"
VAR16= "ufCrm235SimuladorRepasseInvestsmart"
VAR17= "ufCrm235SimuladorRepasseSeguros"
VAR18= "ufCrm235RepasseCambio"
VAR19= "ufCrm235RepasseCredito"
VAR20= "ufCrm235RepasseImovel"



















